generators:
- |-
  apiVersion: fn.kpt.dev/v1alpha1
  kind: RenderHelmChart
  metadata:
    name: demo
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: render-helm-chart
  helmGlobals:
    chartHome: ./charts
  helmCharts:
  - name: coredns
    releaseName: my-coredns
    namespace: coredns
    valuesFile: https://raw.githubusercontent.com/config-sync-examples/helm-components/main/coredns-values.yaml

commonLabels:
  test-case: hydration
